[project]
name = "habit-finance-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.7",
    "django-htmx>=1.26.0",
]

[dependency-groups]
dev = [
    "ty>=0.0.1a24",
]
